export const ActionTypes = {
	PAYSLIPS_REQUEST: "APP_FEEDBACK_REQUEST",
	PAYSLIPS_REQUEST_LOADING: "APP_FEEDBACK_REQUEST_LOADING",
	PAYSLIPS_REQUEST_SUCCESS: "APP_FEEDBACK_REQUEST_SUCCESS",
	PAYSLIPS_REQUEST_FAILURE: "APP_FEEDBACK_REQUEST_FAILURE",
}